version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk
    working_directory: ~/organiser_api
    steps:
      - checkout
      - run:
          name: Build API
          command: dotnet build src/Organiser.Api.sln
workflows:
  version: 2
  organiser_api_dev:
    jobs:
      - build